apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-despachos
  namespace: innovatech
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-despachos
  template:
    metadata:
      labels:
        app: backend-despachos
    spec:
      containers:
        - name: backend-despachos
          # CI/CD reemplazará este valor con la imagen real de ECR
          image: 836626137299.dkr.ecr.us-east-1.amazonaws.com/innovatech/backend-despachos:latest
          ports:
            - containerPort: 8081
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_URL
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DB_PASS
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          # Sin Actuator usamos TCP simple
          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 20