apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: innovatech
type: Opaque
stringData:
  # Compartidas
  MYSQL_ROOT_PASSWORD: ""
  MYSQL_USER: "appuser"
  MYSQL_PASSWORD: ""

  # --- backend-despachos (usa DB_URL completa) ---
  DB_URL: "jdbc:mysql://mysql-svc:3306/db_despachos?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
  DB_USER: "root"
  DB_PASS: ""

  # --- backend-ventas (usa partes separadas) ---
  DB_ENDPOINT: "mysql-svc"
  DB_PORT: "3306"
  DB_NAME: "db_ventas"
  DB_USERNAME: "root"
  DB_PASSWORD: ""
